services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"